apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs-pv
  namespace: airflow-workload
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/mayonfrancis/Developer/airflow-test/dags"