
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-pv-claim
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: airflow-logs-pv