kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: airflow-extra-permissions
  namespace: default
subjects:
  - kind: ServiceAccount
    name: helm-airflow-worker
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow-extra-permissions